### ISSUE TITLE
upgrade docs differ to fresh project setup docs regarding app-routing.module.ts

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus-docs#1399]
**Describe the bug**
When creating a fresh project by following [this guide](https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries-4-x/), the file `app-routing.module.ts` only get's  get's created if answering the question "Would you like to add Angular routing?" with "yes". Doing so is not needed according to the Setup Guide.

When updating an existing < 4 Spartacus project to 4.x, Creation of that file is needed according to the update documentation [here](https://sap.github.io/spartacus-docs/updating-to-version-4/#migrating-to-the-reference-app-structure).

**Tell us the version of Spartacus**
- Library version: 4.2.0

**To Reproduce**
1. Create a fresh Spartacus Project by following the setup guide
2. Notice, that NO file `app-routing.module.ts` get's created

**Expected behavior**
The update documentation leads to the same files as the fresh setup guide

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Additional context**
As having the file `app-routing.module.ts` in our projects does not seem to be neccessary, I am wondering why it is explicitly mentioned in the Spartacus 4 migration docs.

**Comment by Platonn** [comment]
Interesting question. IMHO the docs are correct. But please help me suggest how we can improve it so it's less ambigious. 

## Fresh app since 4.0
Since Spartacus 4.0 there is no need to create a local file `app-routing.module` (via the Angular's CLI question: "Would you like to add Angular routing?"). When installing a fresh Sparatcus 4.0 app (ng add @spartacus/schematics@4), the Spartacus schematics will add automatically into your fresh app.module the import of `AppRoutingModule` that comes from `@spartacus/storefront` (but not a local file):
<img width="397" alt="image" src="https://user-images.githubusercontent.com/4001059/154231417-8a9619a4-ed3b-46e1-8b2f-60d15b6e56b5.png">


## Migrating from 3.x
The guideline about migrating from 3.x to 4.0 shows the **prerequisite steps** how to prepare the app structure **before bumping Spartacus to version 4.0**. The goal of those prerequisite steps is that your app with the new structure should compile successfully, before bumping to 4.0.  Because in 3.x there was no `AppRoutingModule` exported from `@spartacus/storefront` yet, therefore to compile successfully when being on 3.x you needed to create a local file `app-routing.module` yourself.

**TBH After bumping to 4.0 you can drop your local `app-routing.module` and import the `AppRoutingModule` from `@spartacus/storefront` instead.** - Maybe that's what we should add in the end of the migration docs? @janwidmer 

## Why it's important to use `AppRoutingModule` from `@spartacus/storefront`?
`AppRoutingModule` contains Angular's `RouterModule.forRoot({ <settings> }})` with opinionated and important settings for Angular Routing to be compatible with Spartacus.

And in the next releases of 4.x we added there more stuff (like advanced configurable strategies for the scroll restoration)

**Comment by janwidmer** [comment]
@Platonn yes exactly, a hint at the end of the migration docs would be helpful, that the locally created file `app-routing.module.ts` must be deleted again, would be helpful.

Thanks

**Comment by gladius-mtl** [comment]
@janwidmer Thank you for catching this!

The docs have been updated with this PR: https://github.com/SAP/spartacus-docs/pull/1402

**Comment by janwidmer** [comment]
@gladius-mtl perfect, thanks
